name: Build React App
on:
    push:
        branches:
            - development
jobs:
    build:
        runs-on: macos-latest
        steps:
              - name: checkout repo code
                uses: actions/checkout@v3
            
              - name: Yarn setup
                uses: DerYeger/yarn-setup-action@master
                with:
                  node-version: 18

              - run: yarn install
              - run: yarn nx run devops:build
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo code
              uses: actions/checkout@v3
          
            - name: Yarn setup
              uses: DerYeger/yarn-setup-action@master
              with:
                node-version: 18

            - run: yarn install
            - run: yarn nx run devops:test
    deploy:
      needs: test
      runs-on: windows-latest
      permissions:
        contents: write
        pages: write
        id-token: write
      environment:
        name: development
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
          - name: checkout repo
            uses: actions/checkout@v3
            with:
              token: ${{ secrets.GITHUB_TOKEN }}

          - name: Yarn setup
            uses: DerYeger/yarn-setup-action@master
            with:
              node-version: 18

          - name: configure github pages
            uses: actions/configure-pages@v3

          - run: yarn install --immutable
          - run: yarn nx run devops:build

          - name: upload artifacts
            uses: actions/upload-pages-artifact@v1
            with: 
              path: "./dist/apps/devops"

          - name: deploy
            id: deployment
            uses: actions/deploy-pages@v1