name: Build React App
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Inserisci il nome della branch"

jobs:
    build:
        runs-on: macos-latest
        steps:
          - uses: actions/checkout@v4
        
          - run: corepack enable
          - run: corepack prepare yarn@stable

          - uses: actions/setup-node@v4
            with:
              node-version: '18.x'
              check-latest: true
              cache: 'yarn'
              cache-dependency-path: 'yarn.lock'

          - run: yarn install
          - run: yarn nx run devops:build
          - run: corepack disable
    test:
        needs: build
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
        
          - run: corepack enable
          - run: corepack prepare yarn@stable

          - uses: actions/setup-node@v4
            with:
              node-version: '18.x'
              check-latest: true
              cache: 'yarn'
              cache-dependency-path: 'yarn.lock'

          - run: yarn install
          - run: yarn nx run devops:test
          - run: corepack disable
    deploy:
      needs: test
      runs-on: windows-latest
      permissions:
        contents: write
        pages: write
        id-token: write
      environment:
        name: development
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - uses: actions/checkout@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - run: corepack enable
        - run: corepack prepare yarn@stable --activat
        - run: yarn set version stable --yarn-path
            
        - uses: actions/setup-node@v4
          with:
            node-version: '18.x'
            check-latest: true
            cache: 'yarn'
            cache-dependency-path: 'yarn.lock'

        - uses: actions/configure-pages@v4

        - run: yarn install
        - run: yarn nx run devops:build

        - uses: actions/upload-pages-artifact@v2
          with: 
            path: "dist/apps/devops"

        - id: deployment
          uses: actions/deploy-pages@v3
        - run: corepack disable
